# Generated by Django 4.2.7 on 2023-12-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_primary_address',
            field=models.BooleanField(default=False, help_text='Check this if it is the primary address.', verbose_name='Is Primary Address'),
        ),
    ]
