# Generated by Django 4.2.7 on 2024-01-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bavaria (Bayern)'), ('BE', 'Berlin'), ('BB', 'Brandenburg'), ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hesse (Hessen)'), ('NI', 'Lower Saxony (Niedersachsen)'), ('MV', 'Mecklenburg-Western Pomerania (Mecklenburg-Vorpommern)'), ('NW', 'North Rhine-Westphalia (Nordrhein-Westfalen)'), ('RP', 'Rhineland-Palatinate (Rheinland-Pfalz)'), ('SL', 'Saarland'), ('SN', 'Saxony (Sachsen)'), ('ST', 'Saxony-Anhalt (Sachsen-Anhalt)'), ('SH', 'Schleswig-Holstein'), ('TH', 'Thuringia (Thüringen)')], help_text='German state', max_length=2, null=True, verbose_name='State'),
        ),
    ]
