# Generated by Django 4.2.7 on 2024-01-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_country_alter_profile_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, help_text='Format: not required, unique=True', max_length=20, null=True, verbose_name='Postcode'),
        ),
    ]
