# Generated by Django 4.2.7 on 2024-01-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, help_text='Format: not required', max_length=20, null=True, verbose_name='Postcode'),
        ),
    ]
