# Generated by Django 4.2.7 on 2024-01-02 19:19

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='DE', help_text='Format: not required', max_length=2, null=True, verbose_name='Country'),
        ),
    ]
