# Generated by Django 4.2.7 on 2024-01-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, help_text='Format: not required', max_length=80, null=True, verbose_name='State'),
        ),
    ]
