# Generated by Django 4.2.7 on 2024-01-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('online', 'Online Delivery'), ('pickup', 'Pickup')], default='online', max_length=10),
        ),
    ]
