# Generated by Django 4.2.7 on 2024-01-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='county_region_state',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bavaria (Bayern)'), ('BE', 'Berlin'), ('BB', 'Brandenburg'), ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hesse (Hessen)'), ('NI', 'Lower Saxony (Niedersachsen)'), ('MV', 'Mecklenburg-Western Pomerania (Mecklenburg-Vorpommern)'), ('NW', 'North Rhine-Westphalia (Nordrhein-Westfalen)'), ('RP', 'Rhineland-Palatinate (Rheinland-Pfalz)'), ('SL', 'Saarland'), ('SN', 'Saxony (Sachsen)'), ('ST', 'Saxony-Anhalt (Sachsen-Anhalt)'), ('SH', 'Schleswig-Holstein'), ('TH', 'Thuringia (Thüringen)')], default='BW', help_text='Order state', max_length=2, null=True, verbose_name='State'),
        ),
    ]
