# Generated by Django 4.2.7 on 2024-01-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_county_region_state_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='county_region_state',
            field=models.CharField(blank=True, choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bavaria (Bayern)'), ('BE', 'Berlin'), ('BB', 'Brandenburg'), ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hesse (Hessen)'), ('NI', 'Lower Saxony (Niedersachsen)'), ('MV', 'Mecklenburg-Western Pomerania (Mecklenburg-Vorpommern)'), ('NW', 'North Rhine-Westphalia (Nordrhein-Westfalen)'), ('RP', 'Rhineland-Palatinate (Rheinland-Pfalz)'), ('SL', 'Saarland'), ('SN', 'Saxony (Sachsen)'), ('ST', 'Saxony-Anhalt (Sachsen-Anhalt)'), ('SH', 'Schleswig-Holstein'), ('TH', 'Thuringia (Thüringen)')], max_length=100),
        ),
    ]
