# Generated by Django 4.2.7 on 2024-01-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_county_region_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='county_region_state',
            new_name='state',
        ),
    ]
