# Generated by Django 4.2.7 on 2023-12-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small (18cm - 6 portions)'), ('M', 'Medium (26cm - 12 portions)'), ('L', 'Large (36cm - 25 portions)')], default='S', max_length=5),
        ),
    ]
